const players =[
        {
            id: 1,
            avatar: "Le sportif",
            photo : "https://via.placeholder.com/200x200",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 2,
            avatar: "La blonde",
            photo : "https://via.placeholder.com/200x200",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 3,
            avatar: "Le noir",
            photo : "https://via.placeholder.com/200x200",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 4,
            avatar: "Le geek",
            photo : "https://via.placeholder.com/200x200",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :false,
            hadQuestion : false,
        },
        {
            id: 5,
            avatar: "Le rebelle",
            photo : "https://via.placeholder.com/200x200",
            gender: "female",
            skinColor: "light",
            player : "", 
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 6,
            avatar: "Chef d'enteprise",
            photo : "https://via.placeholder.com/200x200",
            gender: "male",
            skinColor: "light",
            player : "", 
            isAlive :true,
            hadQuestion : false,
        }
    ]

    export default players