const players =[
        {
            id: 1,
            avatar: "Le sportif",
            photo : "/img/1.png",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 2,
            avatar: "La blonde",
            photo : "/img/2.png",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 3,
            avatar: "Le noir",
            photo : "/img/3.png",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 4,
            avatar: "Le geek",
            photo : "/img/4.png",
            gender: "male",
            skinColor: "light",
            player : "",
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 5,
            avatar: "Le rebelle",
            photo : "/img/5.png",
            gender: "female",
            skinColor: "light",
            player : "", 
            isAlive :true,
            hadQuestion : false,
        },
        {
            id: 6,
            avatar: "Chef d'enteprise",
            photo : "/img/6.png",
            gender: "male",
            skinColor: "light",
            player : "", 
            isAlive :true,
            hadQuestion : false,
        }
    ]

    export default players